Repository Pacific-Agency/workflows, pull requests merged in 2023-07, with the labels that each got.

#43 feat: Скрипт `Prettier`
  .github/workflows/frontend-lint.yml
Labels: Фича

#42 feat: Скрипты `CI` для бекенда
  .github/workflows/backend-black.yml
  .github/workflows/backend-flake8.yml
  .github/workflows/backend-isort.yml
  .github/workflows/backend-unit-tests.yml
Labels: Фича

#44 fix: Нет лимита времени на тестах
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-lint.yml
  .github/workflows/frontend-test.yml
  .github/workflows/frontend-typecheck.yml
Labels: Баг

#45 chore: Удаление `assignees` и `reviewers` в конфигурации Renovate
  renovate.json
Labels: Chore
